import GridTable from '../../components/reports/GridTable'

export default function DemoReportPage() {
  const headers = [
    {
      displayName: 'In Count',
      children: [
        { displayName: 'Zone', field: 'zone' },
        { displayName: 'Allocation', field: 'allocation' },
        { displayName: 'Weightage', field: 'weightage' },
        { displayName: 'Paid', field: 'paid' },
        { displayName: 'Paid (%)', field: 'paidPercent' },
        { displayName: 'Fully Paid', field: 'fullyPaid' },
        { displayName: 'Fully Paid (%)', field: 'fullyPaidPercent' },
        { displayName: 'Partial Paid', field: 'partialPaid' },
        { displayName: 'Partial Paid (%)', field: 'partialPaidPercent' },
        { displayName: 'Unpaid', field: 'unpaid' },
        { displayName: 'Unpaid (%)', field: 'unpaidPercent' },
        { displayName: 'NPA', field: 'npa' },
        { displayName: 'NPA (%)', field: 'npaPercent' },
      ],
    },
    {
      displayName: 'In Value',
      children: [
        { displayName: 'Allocation', field: 'valueAllocation' },
        { displayName: 'Weightage', field: 'valueWeightage' },
        { displayName: 'Paid', field: 'valuePaid' },
        { displayName: 'Paid(%)', field: 'valuePaidPercent' },
        { displayName: 'Fully Paid', field: 'valueFullyPaid' },
        { displayName: 'Full Paid(%)', field: 'valueFullyPaidPercent' },
        { displayName: 'Partial Paid', field: 'valuePartialPaid' },
        { displayName: 'Partial Paid (%)', field: 'valuePartialPaidPercent' },
        { displayName: 'Unpaid', field: 'valueUnpaid' },
        { displayName: 'Unpaid(%)', field: 'valueUnpaidPercent' },
        { displayName: 'NPA', field: 'valueNpa' },
      ],
    },
  ]

  const rows = [
    {
      id: 1,
      zone: 'Chandigarh Zone',
      allocation: 3533,
      weightage: 7.84,
      paid: 353,
      paidPercent: 9.99,
      fullyPaid: 245,
      fullyPaidPercent: 6.93,
      partialPaid: 108,
      partialPaidPercent: 3.06,
      unpaid: 3177,
      unpaidPercent: 89.92,
      npa: 3,
      npaPercent: 0.08,
      valueAllocation: 68599220.83,
      valueWeightage: 7.77,
      valuePaid: 5173193.33,
      valuePaidPercent: 7.54,
      valueFullyPaid: 3625837.3,
      valueFullyPaidPercent: 5.29,
      valuePartialPaid: 1547356,
      valuePartialPaidPercent: 2.26,
      valueUnpaid: 63313647.5,
      valueUnpaidPercent: 92.3,
      valueNpa: 109680,
    },
    {
      id: 2,
      zone: 'Delhi Zone',
      allocation: 4778,
      weightage: 8.1,
      paid: 396,
      paidPercent: 8.29,
      fullyPaid: 247,
      fullyPaidPercent: 5.17,
      partialPaid: 149,
      partialPaidPercent: 3.12,
      unpaid: 4382,
      unpaidPercent: 91.71,
      npa: 3,
      npaPercent: 0.08,
      valueAllocation: 113574562.68,
      valueWeightage: 12.87,
      valuePaid: 8127961.04,
      valuePaidPercent: 7.16,
      valueFullyPaid: 4949330.99,
      valueFullyPaidPercent: 4.36,
      valuePartialPaid: 3178630.05,
      valuePartialPaidPercent: 2.8,
      valueUnpaid: 105446661.64,
      valueUnpaidPercent: 92.84,
      valueNpa: 0,
    },
    {
      id: 3,
      zone: 'Guwahati Zone',
      allocation: 1396,
      weightage: 3.1,
      paid: 71,
      paidPercent: 5.09,
      fullyPaid: 51,
      fullyPaidPercent: 3.65,
      partialPaid: 20,
      partialPaidPercent: 1.43,
      unpaid: 1323,
      unpaidPercent: 94.77,
      npa: 2,
      npaPercent: 0.14,
      valueAllocation: 13896397.17,
      valueWeightage: 1.58,
      valuePaid: 946771.88,
      valuePaidPercent: 6.77,
      valueFullyPaid: 617347.88,
      valueFullyPaidPercent: 4.41,
      valuePartialPaid: 329424,
      valuePartialPaidPercent: 2.36,
      valueUnpaid: 12050429.29,
      valueUnpaidPercent: 93.09,
      valueNpa: 19076,
    },
    {
      id: 4,
      zone: 'Kolkatta Zone',
      allocation: 4079,
      weightage: 9.05,
      paid: 262,
      paidPercent: 6.42,
      fullyPaid: 217,
      fullyPaidPercent: 5.32,
      partialPaid: 45,
      partialPaidPercent: 1.1,
      unpaid: 3816,
      unpaidPercent: 93.55,
      npa: 1,
      npaPercent: 0.02,
      valueAllocation: 56611303.74,
      valueWeightage: 6.41,
      valuePaid: 2426096,
      valuePaidPercent: 4.29,
      valueFullyPaid: 2005248,
      valueFullyPaidPercent: 3.54,
      valuePartialPaid: 420658,
      valuePartialPaidPercent: 0.74,
      valueUnpaid: 54183995.7,
      valueUnpaidPercent: 95.71,
      valueNpa: 1212,
    },
    {
      id: 5,
      zone: 'Lucknow Zone',
      allocation: 14346,
      weightage: 31.83,
      paid: 546,
      paidPercent: 3.81,
      fullyPaid: 435,
      fullyPaidPercent: 3.03,
      partialPaid: 111,
      partialPaidPercent: 0.77,
      unpaid: 13795,
      unpaidPercent: 96.16,
      npa: 5,
      npaPercent: 0.03,
      valueAllocation: 43714245.81,
      valueWeightage: 49.53,
      valuePaid: 11869280,
      valuePaidPercent: 2.72,
      valueFullyPaid: 9449830.5,
      valueFullyPaidPercent: 2.16,
      valuePartialPaid: 2419449.55,
      valuePartialPaidPercent: 0.55,
      valueUnpaid: 42515718.75,
      valueUnpaidPercent: 97.26,
      valueNpa: 115993,
    },
  ]

  return <GridTable title="Zone Performance Report" headers={headers} rows={rows} columnMapping={{}} />
}
